controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

zapatilla_new:
    path: /sneaker/new
    controller: App\Controller\ZapatillaController::new

login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: ['POST']

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

