version: '3'

services:
  backend:
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./api/
    working_dir: /app
    command: npm start
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: sneakershop
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: