<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMrQfGxw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMrQfGxw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMrQfGxw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMrQfGxw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMrQfGxw\App_KernelDevDebugContainer([
    'container.build_hash' => 'MrQfGxw',
    'container.build_id' => '2d2b7578',
    'container.build_time' => 1711447255,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMrQfGxw');
