<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6MGMAiE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6MGMAiE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6MGMAiE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6MGMAiE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6MGMAiE\App_KernelDevDebugContainer([
    'container.build_hash' => '6MGMAiE',
    'container.build_id' => 'b54d9c32',
    'container.build_time' => 1711449023,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6MGMAiE');
