<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6ssu1Aq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6ssu1Aq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6ssu1Aq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6ssu1Aq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6ssu1Aq\App_KernelDevDebugContainer([
    'container.build_hash' => '6ssu1Aq',
    'container.build_id' => 'bafc534f',
    'container.build_time' => 1717890690,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6ssu1Aq');
